---
title: "Human apicome LCM RNA-seq analysis"
output: html_notebook
author: "Roy Novoselsky"
date: "April 2024"
---

```{r}
rm(list=ls()) 
```

# Dependencies
```{r Warning=F}
library(ggplot2)
library(dplyr)
library(ggrepel)
library(gridExtra)
library(Seurat)
library(ggtext)
library(stringr)
library(ggpubr)
library(tidyr)
library(tidyverse)

directory = getwd()
root_dir =  paste0(unlist(strsplit(directory, '/'))[-length(unlist(strsplit(directory, '/')))], collapse = '/')
source(paste(root_dir,"/functions.R",sep=""))
outputs_dir = paste(directory,"output",sep="/")
if (!dir.exists(outputs_dir)) {dir.create(outputs_dir)}
input_dir = paste(directory,"input",sep="/")

```

# Input data
## read tables
```{r}
human_lcm = read.csv(paste(input_dir,"UMI_TABLE_HUMAN_APICOME_UTAP.csv",sep="/"), row.names=1)

sample_names = data.frame(samples = colnames(human_lcm))
meta = sample_names %>% separate(samples, into = c("apicome", "zone", "patient"), sep = "_")
rownames(meta) = sample_names$samples

human_lcm = CreateSeuratObject(counts=human_lcm,meta.data=meta)
human_lcm$Sample_origin = paste(human_lcm$apicome,human_lcm$zone,sep="_")
Idents(human_lcm) = human_lcm$Sample_origin

```


# Filtering mitochondrial genes
```{r}
types = read.csv(paste(input_dir,"Human_GRch38_101_ensemblBioMart_ref.csv",sep="/"))

types = types[!duplicated(types$external_gene_name), ]
rownames(types) = types$external_gene_name
description = types[types$external_gene_name %in% rownames(human_lcm),c("external_gene_name","description")]

human_lcm = subset(human_lcm,features = rownames(human_lcm)[(rownames(human_lcm) %in% types$external_gene_name[types$gene_biotype == "protein_coding"])])
human_lcm = human_lcm[!grepl("^MT-|MTRNR", rownames(human_lcm)), ]

raw_data = as.data.frame(human_lcm@assays$RNA$counts)

```
## export table
```{r}
write.csv(raw_data,paste(outputs_dir,"/data.csv",sep=""))
```

# plot number of UMIs
```{r}
umi = as.data.frame(colSums(raw_data))
colnames(umi) = "UMI"
umi$apicome = sapply(str_split(rownames(umi), "_"), function(x) x[1])
umi$zone = sapply(str_split(rownames(umi), "_"), function(x) x[2])
umi$apicome[umi$apicome=="apical"] = "Apical samples"
umi$apicome[umi$apicome=="basal"] = "Basal amples"
umi$UMI = log10(umi$UMI)
ggplot(umi, aes( apicome,UMI)) +
  geom_violin(alpha=1, fill="burlywood3",trim=F) +
  geom_boxplot(outlier.shape=NA, width=0.1,fill="cornsilk") +
  geom_jitter(size=2, alpha=0.6, position=position_jitter(width =0.2)) +
  theme_bw(base_size = 18) + 
  theme(legend.position ="none",panel.grid = element_blank(),axis.text=element_text(color="black"))+
  ylab("log10(UMIs)") + xlab(NULL) + ggtitle("") +
  stat_compare_means(label="p.format",label.x = 1.4, label.y = 5.2,size=5)
ggsave(paste(outputs_dir,"/UMIs_violin.pdf",sep=""),width=6,height=6,units="in")

```

# PCA
```{r}
umi_thresh = 20000
exp_thresh = 1e-4

column_sums_df = data.frame(sample = names(colSums(raw_data)),umi = colSums(raw_data))
df = raw_data[,column_sums_df$sample[column_sums_df$umi>umi_thresh]] # filter samples by threshold

df = matnorm(df) # normilize
df_filtered = df[rowMeans(df) >= exp_thresh,] # filter by expression level

results = pca(df_filtered)
plot = results$pca_df
split_df = as.data.frame(do.call(rbind, strsplit(rownames(plot), "_")))
plot = cbind(split_df, plot)
colnames(plot)[1:3] = c("Apicome","Zone","Patient")

xlabel = paste0("PC1 (",round(results$variance$Variance[results$variance$PC == 1] * 100,2),"%)")
ylabel = paste0("PC2 (",round(results$variance$Variance[results$variance$PC == 2] * 100,2),"%)")

plot$Zone = str_to_title(plot$Zone)
plot$Apicome = str_to_title(plot$Apicome)
p1 = ggplot(plot, aes(x=PC1,y=PC2)) +
    geom_point(aes(fill=Apicome), size=4,shape=21,color="black") +
    theme_bw(base_size = 14) +
    scale_fill_manual(values=c("#ee854a","#82c6e2")) +
  theme(legend.position="top",
          legend.background=element_rect(colour="black",linewidth=0.5),
        panel.grid=element_blank(),
        legend.title=element_text(hjust = 0.5),
        axis.text=element_text(color="black")) +
  xlab("") + ylab(ylabel)

p2 = ggplot(plot, aes(x=PC1,y=PC2)) +
    geom_point(aes(fill=Zone), size=4,shape=21,color="black") +
    theme_bw(base_size = 14) +
    scale_fill_manual(values=c("#6acc64","#956cb4")) +
  theme(legend.position="top",
        legend.background=element_rect(colour="black",linewidth=0.5),
        panel.grid=element_blank(),
        legend.title=element_text(hjust = 0.5),
        axis.text=element_text(color="black")) +
  xlab(xlabel) + ylab("")

p3 = ggplot(plot, aes(x=PC1,y=PC2)) +
    geom_point(aes(fill=Patient), size=4,shape=21,color="black") +
    theme_bw(base_size = 14) +
    scale_fill_brewer(palette = "Set1") +
    theme(legend.position="top",
          legend.background=element_rect(colour="black",linewidth=0.5),
          legend.title=element_text(hjust = 0.5),
          panel.grid=element_blank(),
          axis.text=element_text(color="black")) +
  xlab("") + ylab("") +
  guides(fill = guide_legend(ncol = 4))

p1 | p2 | p3 
ggsave(paste(outputs_dir,"/PCA.pdf",sep=""),width=15,height=5,units="in")
```

## PCA of non-chemo patients
```{r}
chemo_patients = c("P1","P5","P8","P13")

plot$chemo = "Non-chemo"
plot$chemo[plot$Patient %in% chemo_patients] = "Chemo"
p4 = ggplot(plot, aes(x=PC1,y=PC2)) +
    geom_point(aes(fill=chemo), size=4,shape=21,color="black") +
    theme_bw(base_size = 14) +
    scale_fill_brewer(palette = "Set1") +
    theme(legend.position=c(0.8,0.2),
          legend.background=element_rect(colour="black",linewidth=0.5),
          legend.title=element_text(hjust = 0.5),
          panel.grid=element_blank(),
          axis.text=element_text(color="black")) +
  xlab("") + ylab("") +labs(fill="Chemotherapy")

p1 + xlab("") + ylab(ylabel) +labs(fill="Apicome") + theme(legend.position = c(0.8,0.2))|
p2 + xlab(xlabel) + ylab("") +labs(fill="Zone") + theme(legend.position = c(0.8,0.2)) |p4

ggsave(paste(outputs_dir,"/PCA_chemo.pdf",sep=""),width=15,height=5,units="in")
```

# Apicome score
```{r}
patients = unique(human_lcm$patient)
medians = raw_data
medians = matnorm(medians)
medians$expression_mean = apply(medians,1,mean)
medians$expression_max = apply(medians,1,max)
medians$expression_min = apply(medians,1,min)

mn = apply(medians,1,median)
pn = min(mn[mn>0])

# # calculate geometric averege of expression
for (cond in c("apical_tip","basal_tip","apical_base","basal_base")){ 
  log_med = log(medians[,grepl(cond,colnames(medians))] + pn)
  medians[[cond]] = apply(log_med, 1, mean)
  medians[[cond]] = exp(medians[[cond]])
}

# calculate geometric averege of ratios
for (p in patients){
  medians[[paste0("ratio_tip_",p)]] = (medians[,paste0("apical_tip_",p)]+pn)/(medians[,paste0("basal_tip_",p)]+pn)
  medians[[paste0("ratio_base_",p)]] = (medians[,paste0("apical_base_",p)]+pn)/(medians[,paste0("basal_base_",p)]+pn)
}
medians[,grepl("ratio_",colnames(medians))] = log(medians[,grepl("ratio_",colnames(medians))],2)

num_ratios = ncol(medians[,grepl("ratio_",colnames(medians))])
medians$SEM = apply(medians[,grepl("ratio_",colnames(medians))],1,sd) / sqrt(num_ratios)

medians$log2_fc = apply(medians[,grepl("ratio_",colnames(medians))],1,mean)
medians$tip_a_b = apply(medians[,grepl("ratio_tip",colnames(medians))],1,mean)
medians$base_a_b = apply(medians[,grepl("ratio_base",colnames(medians))],1,mean)
medians$gene = rownames(medians)

```

# Signed rank test
```{r}
EXP_THRESH = 1e-5

df = raw_data
df = matnorm(df)
expression_mean = apply(df,1,mean)
expression_mean_values = unname(expression_mean)
high_expressed = df[expression_mean >= EXP_THRESH,]
df = df[rownames(high_expressed),]

df$p_val = NA
df$qval = NA
df$p_val_viliChange = NA
df$qval_viliChange = NA
for (g in 1:nrow(df)){
  gene = rownames(df)[g]
  cur_gene_df = NULL
  for (i in 1:length(patients)){
    if (is.null(cur_gene_df)){
        cur_gene_df = df[gene,grepl(paste0(patients[i],"$"),colnames(df))]
        colnames(cur_gene_df) = gsub(paste0("_",patients[i]),"",colnames(cur_gene_df))
        cur_gene_df$patient = patients[i]
      } else {
        cur_gene_df_new = df[gene,grepl(paste0(patients[i],"$"),colnames(df))]
        colnames(cur_gene_df_new) = gsub(paste0("_",patients[i]),"",colnames(cur_gene_df_new))
        cur_gene_df_new$patient = patients[i]
        cur_gene_df = bind_rows(cur_gene_df,cur_gene_df_new)
      }
  }
  apical = c(cur_gene_df$apical_tip,cur_gene_df$apical_base)
  basal = c(cur_gene_df$basal_tip,cur_gene_df$basal_base)
  ratio_tip = (cur_gene_df$apical_tip+pn) / (cur_gene_df$basal_tip+pn)
  ratio_base = (cur_gene_df$apical_base+pn) / (cur_gene_df$basal_base+pn)
  df$p_val[g] = suppressWarnings({wilcox.test(apical,basal,paired=T,alternative="two.sided",exact=T)$p.value})
  df$p_val_viliChange[g] = suppressWarnings({wilcox.test(ratio_tip,ratio_base,paired=T,alternative="two.sided",exact=T)$p.value})
}
df$qval = p.adjust(df$p_val,method="BH")
df$qval_viliChange = p.adjust(df$p_val_viliChange,method="BH")
df$gene = rownames(df)
```
## add qval to "medians"
```{r}
medians = merge(medians, df[,c("gene","p_val","qval","p_val_viliChange","qval_viliChange")], by="gene",all=T)
rownames(medians) = medians$gene
medians[,grepl("apical_tip_|apical_base_|basal_tip_|basal_base_",colnames(medians))] = NULL

```

# MA with selected genes
```{r}
QVAL_THRESH = 0.25
genes = c("CPS1","DSP","MYH14","CDH1","APOA4", "SLC5A1")

plot = medians
plot$signif = "no"
plot$signif[plot$qval < QVAL_THRESH] = "signif"
plot$signif[plot$gene %in% genes] = "selected"
plot$signif = factor(plot$signif, levels = c("no", "signif", "selected"))
plot = arrange(plot, signif)

plot$log10_expression = log(plot$expression_mean,10)

ggplot(plot, aes(log10_expression,log2_fc)) +
  geom_point(aes(color=signif,fill=signif, size=signif),shape=21) +
  geom_text_repel(aes(label=gene),data=plot[plot$signif == "selected",],max.overlaps = 30,color="red",size=5) +
  scale_color_manual(values = c("no"="black","signif"="blue","selected"="red"),name="Significant",guide = "none") +
  scale_fill_manual(values = c("no"="black","signif"="blue","selected"="blue"),name="Significant",guide = "none")+
  scale_size_manual(values=c("no"=1,"signif"=1,"selected"=3))+
  xlab(expression("log10(mean expression)")) +
  ylab(expression("log2(apical/basal)")) +
  theme_bw(base_size=20)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),legend.position="none",axis.text.y=element_text(color="black"))

ggsave(paste(outputs_dir,"MA_with_selected.pdf",sep="\\"),width=6,height=6,units="in")

```

# GSEA
## run GSEA
```{r}
exp_thresh = 0
to_gsea = medians[medians$expression_mean >= exp_thresh,]
gsea = GSEA_function(to_gsea$gene,to_gsea$log2_fc,organism = "Homo sapiens",qval_threshold = 1)
gsea$GSEA$direction[gsea$GSEA$direction=="upregulated"] = "z_Apical"
gsea$GSEA$direction[gsea$GSEA$direction=="downregulated"] = "Basal"

```

## plot
```{r}
qval_thresh = 0.1
plot = gsea$GSEA[gsea$GSEA$padj <= qval_thresh]
p = plot_GSEA_dotplot(plot,alpha=F,title=NULL,grid=T) 

p + theme(legend.position = c(0.25,0.75)) 

ggsave(paste(outputs_dir,"/GSEA_mRNA.pdf",sep=""),width=5,height=5,units="in")
```
## plot a single pathway 
```{r}
genes = gsea$GSEA$leadingEdge[grepl("oxida",gsea$GSEA$pathway,ignore.case = T)][[1]]

plot = medians

plot$signif = F
plot$signif[plot$gene %in% genes] = T
plot = plot[order(plot$signif),]

plot$log10_expression = log10(plot$expression_mean)
ggplot(plot, aes(log10_expression,log2_fc,color=signif)) +
  geom_point() +
  geom_text_repel(aes(label=gene,color=signif),data=plot[plot$signif==T,],max.overlaps = 5,size=4) +
  xlab(expression("log10(max expression)")) + 
  ylab(expression("log2(apical/basal)")) +
  theme_bw(base_size=14)+
  scale_size_manual(values=c("no"=1,"signif"=1,"selected"=3))+
  scale_color_manual(values=c("blue","red")) +
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),legend.position="none")
```

## export
```{r}
to_save = gsea$GSEA
to_save$leadingEdge = NULL
to_save$direction[to_save$direction=="z_Apical"] = "Apical"
to_save = to_save[order(to_save$NES,decreasing = T),]
write.csv(to_save, paste(outputs_dir,"/export_gsea.csv",sep=""),row.names = F)
shell.exec(paste(outputs_dir,"/export_gsea.csv",sep=""))
```

# plot apicome across villi zones
```{r}
EXPRESSION_THRESHOLD = 1e-4
FC_THRESH = 0

plot = medians[medians$expression_mean > EXPRESSION_THRESHOLD,]

plot$signif = F
plot$signif[(plot$tip_a_b > FC_THRESH | plot$tip_a_b < -FC_THRESH) |
                       (plot$base_a_b > FC_THRESH | plot$base_a_b < -FC_THRESH)] = T

plot$qval_viliChange_log10 = -log(plot$qval_viliChange,10)
plot$log10_expression = log(plot$expression_mean,10)

ggplot(plot, aes(tip_a_b, base_a_b)) +
  geom_hline(yintercept=0, linetype="dashed",alpha = 0.3) +
  geom_vline(xintercept=0, linetype="dashed",alpha = 0.3) +
  geom_point(aes(fill=qval_viliChange_log10),color="black",shape=21,size=1)+
  geom_text_repel(data=plot[plot$signif == T,],aes(tip_a_b, base_a_b,label=gene),max.overlaps = 15, size=3) +
  ggtitle("") +
  theme_bw(base_size=18) +
  theme(axis.line = element_line(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text=element_text(color="black"),legend.position="none")+
  xlab("log2(apical/basal) - Villus top") + ylab("log2(apical/basal) - Villus bottom") +
  
  scale_fill_gradient(low="black",high="black",name="log10(q-val)")+
  stat_cor(aes(tip_a_b, base_a_b), digits=2,method = "spearman", inherit.aes=F,label.y.npc = "top",label.x.npc = "left",size=5)
  
ggsave(paste(outputs_dir,"/scatter_general.pdf",sep=''),width=8,height=8,units="in")

```

# export data
```{r}
saveRDS(human_lcm,paste(outputs_dir,"/export_LCM_SEURAT.rds",sep=""))
write.csv(human_lcm@meta.data, paste(outputs_dir,"/export_metadata.csv",sep=""))
write.csv(human_lcm@assays$RNA$counts, paste(outputs_dir,"/export_data.csv",sep=""))
write.csv(medians, paste(outputs_dir,"/medians.csv",sep=""))
```
