---
title: "Mouse apicome LCM RNA-seq analysis"
output: html_notebook
author: "Roy Novoselsky"
date: "April 2024"
---

```{r}
rm(list=ls()) 
```

# Dependencies
```{r Warning=F}
library(ggplot2)
library(dplyr)
library(ggrepel)
library(gridExtra)
library(readxl)
library(Seurat)
library(ggtext)
library(stringr)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(viridis)
library(tidyr)
library(colorspace)

directory = getwd()
root_dir =  paste0(unlist(strsplit(directory, '/'))[-length(unlist(strsplit(directory, '/')))], collapse = '/')
source(paste(root_dir,"/functions.R",sep=""))
```
# type of pipeline, which genes to filter
(uncomment )

# Input data
## path
```{r}
input_dir = paste(directory,"input",sep="/")
outputs_dir = paste(directory,"output",sep="/")

if (!dir.exists(outputs_dir)) {dir.create(outputs_dir)}
```

## read data
```{r}
lcm = read.csv(paste(input_dir,"UMI_TABLE_mouse_APICOME_UTAP.csv",sep="/"), row.names=1)
lcm = lcm[,!grepl("mid|stroma|whole",colnames(lcm))]
sample_names = data.frame(samples = colnames(lcm))
meta = sample_names %>% separate(samples, into = c("apicome", "zone", "mouse"), sep = "_")
rownames(meta) = sample_names$samples
lcm = CreateSeuratObject(counts=lcm,meta.data=meta)
lcm$Sample_origin = paste(lcm$apicome,lcm$zone,sep="_")

```

# QC plots
```{r}
Idents(lcm) = lcm$Sample_origin

lcm$zone = str_split_i(lcm$Sample_origin,pattern="_",2)
lcm$apicome = str_split_i(lcm$Sample_origin,pattern="_",1)
```

```{r}
THRESHOLD_UMI = 10000
lcm[["percent.mito"]] = PercentageFeatureSet(lcm, pattern = "^mt-")
lcm[["percent.ribo"]] = PercentageFeatureSet(lcm, pattern ="^Rp[sl]")
```

```{r}
meta = lcm@meta.data
meta$color = "black"
meta$color[meta$nCount_RNA < THRESHOLD_UMI] = "red"
meta$sample_names_mouse = paste(meta$Sample_origin,meta$mouse,sep="_")
ggplot(meta, aes(x=sample_names_mouse,y=nCount_RNA,fill=color)) + 
  geom_col()+ 
  coord_flip() +
  theme_bw(base_size=18)  + 
  theme(axis.text.y = element_markdown(),axis.title.x = element_blank(),axis.title.y = element_blank())+ 
  scale_fill_identity()+
  geom_hline(yintercept=THRESHOLD_UMI, linetype="dashed", color = "orange")+
  ggtitle("number of UMIs")
# ggsave(paste(outputs_dir,"/UMIs.pdf",sep=''),width=12,height=8,units="in")

ggplot(meta, aes(x=sample_names_mouse,y=nFeature_RNA,fill=color)) + 
  geom_col()+ 
  coord_flip() + 
  theme_bw(base_size=11)  + 
  theme(axis.text.y = element_markdown(),axis.title.x = element_blank(),axis.title.y = element_blank())+ 
  scale_fill_identity()+
  ggtitle("number of unique genes")
# ggsave(paste(outputs_dir,"/nFeatures.pdf",sep=''),width=12,height=8,units="in")

ggplot(meta, aes(x=sample_names_mouse,y=percent.mito,fill=color)) + 
  geom_col()+ 
  coord_flip() + 
  theme_bw(base_size=11)  + 
  theme(axis.text.y = element_markdown(),axis.title.x = element_blank(),axis.title.y = element_blank())+ 
  scale_fill_identity()+
  ggtitle("% of mitochondrial genes")
# ggsave(paste(outputs_dir,"/mito_precent.pdf",sep=''),width=12,height=8,units="in")

ggplot(meta, aes(x=sample_names_mouse,y=percent.ribo,fill=color)) + 
  geom_col()+ 
  coord_flip() + 
  theme_bw(base_size=11)  + 
  theme(axis.text.y = element_markdown(),axis.title.x = element_blank(),axis.title.y = element_blank())+ 
  scale_fill_identity()+
  ggtitle("% of ribosomal genes")
# ggsave(paste(outputs_dir,"/ribo_precent.pdf",sep=''),width=12,height=8,units="in")

```

# Filtering
```{r}
lcm = subset(lcm, subset=nCount_RNA > THRESHOLD_UMI)

```

## export table
```{r}
raw_data = as.data.frame(lcm@assays$RNA$counts)
write.csv(lcm@assays$RNA$counts,paste(outputs_dir,"/data_all_genes.csv",sep=""))
```

## Filtering protein coding genes
```{r}
types = read.csv(paste(input_dir,"mouse_GRcm38_101_ensemblBioMart_ref.csv",sep="/"))
types = types[!duplicated(types$external_gene_name), ]
rownames(types) = types$external_gene_name
description = types[types$external_gene_name %in% rownames(lcm),c("external_gene_name","description")]

lcm = subset(lcm,features = rownames(lcm)[(rownames(lcm) %in% types$external_gene_name[types$gene_biotype == "protein_coding"])])
lcm = lcm[!grepl("^mt-", rownames(lcm)), ]

```

## export table
```{r}
raw_data = as.data.frame(lcm@assays$RNA$counts)
write.csv(lcm@assays$RNA$counts,paste(outputs_dir,"/data.csv",sep=""))
```

# Normalization
```{r}
lcm = NormalizeData(object = lcm,normalization.method="RC",scale.factor = 1, verbose = F)
lcm = FindVariableFeatures(object = lcm, verbose = F)
```

# PCA
## scale data + PCA
```{r}
lcm = ScaleData(lcm, features=rownames(lcm), verbose = F)
lcm = RunPCA(object = lcm,features=VariableFeatures(object= lcm),npcs=7, verbose = F)
```

## PC1+PC2 plot
```{r}
p1 = DimPlot(lcm, reduction = 'pca', group.by="zone", pt.size = 4) + 
  xlab("") +
  ylab(paste("PC2 (",round(lcm@reductions$pca@stdev[2],1),"%)",sep="")) +
  theme(legend.position=c(0.5,0.2),legend.background=element_rect(colour="black",linewidth=0.5)) 

p2 = DimPlot(lcm,group.by="apicome", pt.size = 4,  reduction = 'pca') + 
  xlab(paste("PC1 (",round(lcm@reductions$pca@stdev[1],1),"%)",sep="")) +
  ylab(paste("")) +
  theme(legend.position=c(0.5,0.2),legend.background=element_rect(colour="black",linewidth=0.5)) 

grid.arrange(p1,p2,ncol=2,top="PCA of LCM samples")
plot = arrangeGrob(p1,p2,ncol=2,top="PCA of LCM samples")

# ggsave(paste(outputs_dir,"/PCA.pdf",sep=''),width=12,height=6,units="in",plot=plot)

DimPlot(lcm,group.by="zone",shape.by="apicome", pt.size = 4,  reduction = 'pca') + 
  xlab(paste("PC1 (",round(lcm@reductions$pca@stdev[1],1),"%)",sep="")) +  
  ylab(paste("PC2 (",round(lcm@reductions$pca@stdev[2],1),"%)",sep="")) +
  ggtitle("PCA of LCM samples") +
  labs(color='Villi axis', shape="Apicome") 

# ggsave(paste(outputs_dir,"/PCA_apicome.pdf",sep=''),width=10,height=8,units="in")


```

# Apicome score
```{r}
mouse = unique(lcm$mouse)
medians = raw_data
medians = matnorm(medians)
medians$expression_mean = apply(medians,1,mean)
medians$expression_max = apply(medians,1,max)
medians$expression_min = apply(medians,1,min)

mn = apply(medians,1,median)
pn = min(mn[mn>0])

# # calculate geometric averege of expression
for (cond in c("apical_tip","basal_tip","apical_base","basal_base")){ 
  log_med = log(medians[,grepl(cond,colnames(medians))] + pn)
  medians[[cond]] = apply(log_med, 1, mean)
  medians[[cond]] = exp(medians[[cond]])
}

# calculate geometric averege of ratios
for (p in mouse){
  if (paste0("apical_tip_",p) %in% colnames(medians) &
     paste0("basal_tip_",p) %in% colnames(medians)){
  medians[[paste0("ratio_tip_",p)]] = (medians[,paste0("apical_tip_",p)]+pn)/(medians[,paste0("basal_tip_",p)]+pn)}
  if (paste0("apical_base_",p) %in% colnames(medians) &
     paste0("basal_base_",p) %in% colnames(medians)){
  medians[[paste0("ratio_base_",p)]] = (medians[,paste0("apical_base_",p)]+pn)/(medians[,paste0("basal_base_",p)]+pn)}
}
medians[,grepl("ratio_",colnames(medians))] = log( medians[,grepl("ratio_",colnames(medians))],2)

medians$log2_fc = apply(medians[,grepl("ratio_",colnames(medians))],1,mean)
medians$tip_a_b = apply(medians[,grepl("ratio_tip",colnames(medians))],1,mean)
medians$base_a_b = apply(medians[,grepl("ratio_base",colnames(medians))],1,mean)
medians$gene = rownames(medians)
```

# signed rank test
```{r}
EXP_THRESH = 1e-4

df = raw_data
df = matnorm(df)
expression_mean = apply(df,1,mean)
expression_mean_values = unname(expression_mean)
high_expressed = df[expression_mean >= EXP_THRESH,]
df = df[rownames(high_expressed),]

df$p_val = NA
df$qval = NA
df$p_val_viliChange = NA
df$qval_viliChange = NA
for (g in 1:nrow(df)){
  gene = rownames(df)[g]
  cur_gene_df = NULL
  for (i in 1:length(mouse)){
    if (is.null(cur_gene_df)){
        cur_gene_df = df[gene,grepl(paste0(mouse[i],"$"),colnames(df))]
        colnames(cur_gene_df) = gsub(paste0("_",mouse[i]),"",colnames(cur_gene_df))
        cur_gene_df$patient = mouse[i]
      } else {
        cur_gene_df_new = df[gene,grepl(paste0(mouse[i],"$"),colnames(df))]
        colnames(cur_gene_df_new) = gsub(paste0("_",mouse[i]),"",colnames(cur_gene_df_new))
        cur_gene_df_new$patient = mouse[i]
        cur_gene_df = bind_rows(cur_gene_df,cur_gene_df_new)
      }
  }
  apical = c(cur_gene_df$apical_tip,cur_gene_df$apical_base)
  basal = c(cur_gene_df$basal_tip,cur_gene_df$basal_base)
  ratio_tip = (cur_gene_df$apical_tip+pn) / (cur_gene_df$basal_tip+pn)
  ratio_base = (cur_gene_df$apical_base+pn) / (cur_gene_df$basal_base+pn)
  df$p_val[g] = suppressWarnings({wilcox.test(apical,basal,paired=T,alternative="two.sided",exact=T)$p.value})
  df$p_val_viliChange[g] = suppressWarnings({wilcox.test(ratio_tip,ratio_base,paired=T,alternative="two.sided",exact=T)$p.value})
}
df$qval = p.adjust(df$p_val,method="BH")
df$qval_viliChange = p.adjust(df$p_val_viliChange,method="BH")
df$gene = rownames(df)

```

## add qval to "medians"
```{r}
medians = merge(medians, df[,c("gene","p_val","qval","p_val_viliChange","qval_viliChange")], by="gene",all=T)
rownames(medians) = medians$gene
medians[,grepl("apical_tip_|apical_base_|basal_tip_|basal_base_",colnames(medians))] = NULL
```

# MA with selected genes
```{r}
QVAL_THRESH = 0.35
genes = c("Net1","Apob","Pigr","Cdh1","Cyb5r3", "Alpi")

plot = medians
plot$signif = "no"
plot$signif[plot$qval < QVAL_THRESH] = "signif"
plot$signif[plot$gene %in% genes] = "selected"
plot$signif = factor(plot$signif, levels = c("no", "signif", "selected"))
plot = arrange(plot, signif)

plot$log10_expression = log(plot$expression_mean,10)

ggplot(plot, aes(log10_expression,log2_fc)) +
  geom_point(aes(color=signif,fill=signif, size=signif),shape=21) +
  geom_text_repel(aes(label=gene),data=plot[plot$signif == "selected",],max.overlaps = 30,color="red",size=5) +
  scale_color_manual(values = c("no"="black","signif"="blue","selected"="red"),name="Significant",guide = "none") +
  scale_fill_manual(values = c("no"="black","signif"="blue","selected"="blue"),name="Significant",guide = "none")+
  scale_size_manual(values=c("no"=1,"signif"=1,"selected"=3))+
  xlab(expression("log10(mean expression)")) +
  ylab(expression("log2(apical/basal)")) +
  theme_bw(base_size=20)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),legend.position="none")

ggsave(paste(outputs_dir,"MA_with_selected.pdf",sep="\\"),width=6,height=6,units="in")

```

## plot all significant genes
```{r}
EXPRESSION_THRESHOLD = 1e-5

plot = medians[medians$expression_mean > EXPRESSION_THRESHOLD & !is.na(medians$qval_viliChange),]


plot$qval_viliChange_log10 = -log(plot$qval_viliChange,10)
plot$log10_expression = log(plot$expression_mean,10)

ggplot(plot, aes(tip_a_b, base_a_b)) +
  geom_hline(yintercept=0, linetype="dashed",alpha = 0.3) +
  geom_vline(xintercept=0, linetype="dashed",alpha = 0.3) +
  geom_point(aes(fill=qval_viliChange_log10),color="black",shape=21)+
  ggtitle("") +
  theme_bw(base_size=18) +
  theme(axis.line = element_line(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.text=element_text(color="black"))+
  xlab("log2(apical/basal) - Villus tip") + ylab("log2(apical/basal) - Villus bottom") +
  
  scale_fill_gradient(low="red",high="yellow",name="log10(q-val)")+
  stat_cor(aes(tip_a_b, base_a_b), digits=2,method = "spearman", inherit.aes=F,label.y.npc = "top",label.x.npc = "left",size=5)
  
ggsave(paste(outputs_dir,"/scatter_general.pdf",sep=''),width=8,height=8,units="in")

```

# export data
```{r}
saveRDS(lcm,paste(outputs_dir,"/export_LCM_SEURAT.rds",sep=""))
write.csv(lcm@meta.data, paste(outputs_dir,"/export_metadata.csv",sep=""))
write.csv(lcm@assays$RNA$counts, paste(outputs_dir,"/export_data.csv",sep=""))
write.csv(medians, paste(outputs_dir,"/medians.csv",sep=""))
```
